### PR TITLE
fix multi-thread pull with autoproj 2

### PR DESCRIPTION
**Pull request by planthaber**

### CODE REVIEW

**Comment by 2maz** [comment]
How does that affect autoproj v1 installations?

**Comment by planthaber** [comment]
Works fine on my checkout, but btw: 

isn't https://github.com/planthaber/simulation-package_set/blob/23ae6fae81decd6f98132dbb9449d4a3f0f6b45a/source.yml#L8
An obsolete entry now?

**Comment by 2maz** [comment]
Ok regarding the first and regarding the obsolete entry I assume it is. Could you verify?

**Comment by planthaber** [comment]
indeed obsolete

**Pull request merged**
